"""add enable_suggestions to domains

Revision ID: 4365921920ee
Revises: e56a39dec2da
Create Date: 2026-03-25 02:39:33.998630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4365921920ee'
down_revision: Union[str, None] = 'e56a39dec2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_domain_files_domain_id'), table_name='domain_files')
    op.alter_column('domains', 'enable_suggestions',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('domains', 'total_chunk_count')
    op.drop_index(op.f('idx_reset_token'), table_name='password_reset_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reset_token'), 'password_reset_tokens', ['token'], unique=False)
    op.add_column('domains', sa.Column('total_chunk_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('domains', 'enable_suggestions',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_domain_files_domain_id'), 'domain_files', ['domain_id'], unique=False)
    # ### end Alembic commands ###
