"""add chunk_count to domains

Revision ID: b1696210361a
Revises: 4365921920ee
Create Date: 2026-03-25 02:50:41.138492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1696210361a'
down_revision: Union[str, None] = '4365921920ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('chunk_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'chunk_count')
    # ### end Alembic commands ###
